import type { Metadata } from 'next';
import { Sen } from 'next/font/google';
import '@/app/globals.scss';
import { Header } from '@/widgets/Header/ui/Header';
import { Footer } from '@/widgets/Footer';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const sen = Sen({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-sen',
});

export const metadata: Metadata = {
  title: 'Modsen Client Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sen.className}>
        <Header />
        {children}
        <Footer />
        <ToastContainer />
      </body>
    </html>
  );
}
